### ISSUE TITLE
Adaptive N-back test analysis thought

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/dataproc.iquizoo#12]
As far as I know, it is problematic to use an adaptive version of N-back test in measuring cognition. It is hard to get some proper indices because of the different difficulties of different versions of N-back. 3-back is obviously harder than 2-back, but it is even harder to know how much harder it is.

**Comment by Blockhead-yj** [comment]
We don't know how a brain treat 2-back and 3-back differently, and how the difficulty differ in a brain. But I think the average correct rate of 2-back and 3-back among enough people can reflect the relative difficulty between them. That is, we can define the difficulty of a problem by its average correct rate among people. If 100% people answer the problem correctly, it is reasonable to set the difficulty of the problem 0; If no people can answer the question correctly, the difficulty of the question can be set as infinite.

**Comment by psychelzh** [comment]
Adaptive N-back is currently deprecated. Closing.
