### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/dataproc.iquizoo#31]
The same reason from psychelzh/tarflow.iquizoo#27.

Candidates:

* {preproc.iq}
* {prep.iquizoo}
* {iqprep}

@Blockhead-yj Need your suggestion, too.

**Comment by Blockhead-yj** [comment]
prep.iqz or prep.iquizoo is good

**Comment by psychelzh** [comment]
Considering *prep.iqz*. Thanks!

**Comment by psychelzh** [comment]
No more hesitating and take the first consideration.
